### PR TITLE
Fix pet parsing

### LINKED ISSUE #152: Fix pet parsing under some cases
**Describe the bug**
Some logs uploaded may fail to be parsed due to special cases.

The main issue is a panic on the thread running the parser:
```
thread '<unnamed>' panicked at 'attempt to add with overflow', Backend/src/modules/live_data_processor/tools/cbl_parser/wow_vanilla/parser.rs:1164:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
We end up with a `GUID` that is too long.

Another case is trying to find a summon that does not exist, due to combat log containing an empty string instead of the classical `nil` string.

**To Reproduce**
1. Upload the given log : [WoWCombatLog.txt.zip](https://github.com/Geigerkind/LegacyPlayersV3/files/5803860/WoWCombatLog.txt.zip)
4. See error on backend

**Expected behavior**
Parsing should not panic, and the raid should show up on the server.

### PR DESCRIPTION
**Pull request by gfriloux**
We might end up with an overflow on the pet GUID or get an empty string
when parsing the pet name.

This fixes these special cases.

The overflow part is fixed by @Shino while i was investigating it with him.

Fixes #152

### CODE REVIEW

File: Backend/src/modules/live_data_processor/tools/cbl_parser/wow_vanilla/parser.rs [hunk 1]
```diff
@@ -1051,7 +1051,7 @@ impl CombatLogParser for WoWVanillaParser {
                 participant.guild_args = Some((guild_name.to_string(), guild_rank_name.to_string(), guild_rank_index));
             }
 
-            if pet_name != "nil" {
+            if pet_name != "nil" && pet_name != "" {
```
Comment (Geigerkind) [inline Backend/src/modules/live_data_processor/tools/cbl_parser/wow_vanilla/parser.rs:1054]: Use this function: https://doc.rust-lang.org/std/string/struct.String.html#method.is_empty-1

File: Backend/src/modules/live_data_processor/tools/cbl_parser/wow_vanilla/parser.rs [hunk 2]
```diff
@@ -1051,7 +1051,7 @@ impl CombatLogParser for WoWVanillaParser {
                 participant.guild_args = Some((guild_name.to_string(), guild_rank_name.to_string(), guild_rank_index));
             }
 
-            if pet_name != "nil" && pet_name != "" {
+            if pet_name != "nil" && pet_name.is_empty() {
```
Comment (gfriloux) [inline Backend/src/modules/live_data_processor/tools/cbl_parser/wow_vanilla/parser.rs]: As @Geigerkind noticed while reviewing code, i inverted the test.

**Review by gfriloux — COMMENTED** [review]
Test is fixed on latest commit.
